### ISSUE TITLE
coverage combine rejects .coverage_covimerage

### ISSUE THREAD

**Issue by willjp** [Vimjas/covimerage#80]
# Question

`coverage` subparsers (ex: combine, xml, ...) now reject the generated `.coverage_covimerage` file. `covimerage xml` continues to work. 

```
Coverage.py warning: 
Couldn't use data file 
'~/.vim/bundle/myplugin/.coverage_covimerage': file is not a database
No usable data files
```

`.coverage_covimerage` contains

``` 
!coverage.py: This is a private format, don't read it directly!{"lines":{"/home/will/.vim/bundle/myplugin/plugin/taskmage.vim":[7,9,12,13,14,15,16,17,18,25,33,46,47,48,49,50,51,52,53,54,55,56,57,58,65,66,68,69,70,71,72,73,80,81,82,83],"/home/will/.vim/bundle/myplugin/autoload/taskmage/searchbuffer.vim":[3,8,20,25,29,36,41,42,46,50,51,52,55,56,59,60,61,64,66,70,73,74,75,76,80,83,87,92,94,97,100,101,102,105,110,116,119,120,121,122,125,129,137,139,142,144,147,150,152,155,156,159,169,170,171,176,179,180,181,182,186,189,190,192,194,195,199,208,209,213]},"file_tracers":{"/home/will/.vim/bundle/myplugin/plugin/taskmage.vim":"covimerage.CoveragePlugin","/home/will/.vim/bundle/myplugin/autoload/taskmage/searchbuffer.vim":"covimerage.CoveragePlugin"}}
```

This may be too obscure to merit your attention (I suspect I'll need to change my workflow) , but I thought I would bring it up anyways.

Has the output format always been yaml?

**Comment by willjp** [comment]
In case it is relevant, this is the workflow I have been using so far:

``` bash
# 1. get vim coverage
covimerage run \
    --source plugin/viml \
    vim -Nu tests/resources/vimrc -c Vader! tests/vim/*

# 2. get python coverage
python setup.py test --addopts --cov=plugim/python

# 3. assemble both reports
coverage combine .coverage .coverage_covimerage

# 4. generate html report
coverage html
```

**Comment by blueyed** [comment]
> '~/.vim/bundle/myplugin/.coverage_covimerage': file is not a database

Is this using coverage 5 already?

**Comment by blueyed** [comment]
https://github.com/Vimjas/covimerage/pull/81 might be relevant.

Coverage.py 5.0a5 should work still (but needs adjustments then maybe in the workflow), later versions will not work.

#81 should prevent you from using 5.0a5 by default.

**Comment by blueyed** [comment]
> Has the output format always been yaml?

It is custom JSON there.
Coverage 5 adds a new format, and after 5.0a5 does not handle the old format anymore.

It looks like you have Coverage.py > 5.0a5 already (check `pip freeze`).

**Comment by blueyed** [comment]
I've released 0.2.0.
It should help with pinning the version better, and also provides the Coverage.py version with its `--version` output.
Please give it a try.

**Comment by willjp** [comment]
oh wow thank you so much, I have family over today, I'll try it out tonight and let you know.

Thank you so much!

**Comment by willjp** [comment]
Thanks very much once again for helping :). 

I installed the latest covimerage, the problem persisted. It reported coverage `5.0a5` .

```
$ covimerage --version 

covimerage, version 0.1.7.dev11+g83018f3 (using Coverage.py 5.0a5)
```

Since the CLI command I am using is from coverage, I also made sure that the coverage version matched.

```
$ coverage help version

Coverage.py, version 5.0a5 with C extension
Full documentation is at https://coverage.readthedocs.io/en/coverage-5.0a5
```

I quickly tried all of the 5.x releases - and it did not work in any of them. *But* **after installing 4.5.4, it worked flawslessly again :).** 


This was clearly my own blunder - pypi/arch package repo both still list 4.5.4 as the newest version. I must have installed the latest version from github for some reason.

Thank you very much for the help, and I hope you have a great day.

**Comment by blueyed** [comment]
Glad we've figured it out.

So it appears that Coverage.py 5.0a5 is still compatible with covimerage internally, but then the output is not (without additional config).
Anyway, with Coverage.py 5 the old output will not be supported anymore anyway, and I've looked a bit into making covimerage more compatible with it already.

Thanks for reporting back, I hope you had a great day.. :)
